subprojects {
    apply plugin: 'java'

    java.toolchain.languageVersion = JavaLanguageVersion.of(8)

    jar {
        manifest {
            attributes([
                    "Specification-Title": "${mod_id}",
                    "Specification-Vendor": "${mod_authors}",
                    "Specification-Version": "1",
                    "Implementation-Title": "${mod_name}",
                    "Implementation-Version": "${mod_version}",
                    "Implementation-Vendor": "${mod_authors}",
                    "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
            ])
        }
    }

    repositories {
        mavenCentral()

        maven {
            url "https://cursemaven.com"
            content {
                includeGroup "curse.maven"
            }
        }
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.encoding = 'UTF-8'
        it.options.release = 8
    }

    tasks.withType(GenerateModuleMetadata) {
        enabled = false
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    // Shared method to create replace properties map
    ext.getReplaceProperties = {
        return [
                minecraft_version: minecraft_version,
                minecraft_version_range: minecraft_version_range,
                forge_version: forge_version,
                forge_version_range: forge_version_range,
                loader_version_range: loader_version_range,
                mod_id: mod_id,
                mod_name: mod_name,
                mod_license: mod_license,
                mod_version: mod_version,
                mod_authors: mod_authors,
                mod_description: mod_description,
                mod_page: mod_page,
                mod_source: mod_source,
                mod_issues: mod_issues,
                mod_group: mod_group,
                version: mod_version,
                archivesBaseName: archivesBaseName
        ]
    }
}