# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.daemon=false

# Environment Properties
minecraft_version=1.12.2
minecraft_version_range=[1.12.2,1.13)

# Mappings
mapping_channel=stable
mapping_version=39-1.12

# Forge Properties
# Check https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=14.23.5.2860
forge_version_range=[14.23.5,14.24)
loader_version_range=[14,15)

# Mod Properties
mod_id=llovelyr
mod_name=LovelyRobot Legacy
mod_version=1.0
mod_group=net.msymbios.llovelyr
mod_authors=MSymbios
mod_license=MIT License
mod_description=Example mod description.
mod_page=https://www.curseforge.com/minecraft/mc-mods/reboot-lovelyrobot
mod_source=https://github.com/heria-zone/reboot-lovely-robot
mod_issues=https://github.com/heria-zone/reboot-lovely-robot/issues
# TODO: Add to the mcmod.info
mod_update=https://github.com/heria-zone/reboot-lovely-robot/docs/updates/llovelyr.json