subprojects {

    apply plugin: 'java'
    java.toolchain.languageVersion = JavaLanguageVersion.of(17)

    repositories {
        mavenCentral()

        maven {
            url "https://cursemaven.com"
            content {
                includeGroup "curse.maven"
            }
        }
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.encoding = 'UTF-8'
        it.options.release = 17
    }

    task wrapper(type: Wrapper) {
        gradleVersion = "${gradle_version}"
    }

    tasks.withType(GenerateModuleMetadata) {
        enabled = false
    }
}