modLoader="javafml"
loaderVersion="${forge_version_range}"
license="${mod_license}"
issueTrackerURL="${mod_issues}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''${mod_description}'''
authors="${mod_authors}"
displayURL="${mod_homepage}"

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

# Uncomment if using GeckoLib
#[[dependencies.${mod_id}]]
#modId="geckolib"
#mandatory=true
#versionRange="[4.7.3,)"
#ordering="NONE"
#side="BOTH"

# Uncomment if using Lovely Lib
#[[dependencies.${mod_id}]]
#modId="lovelylib"
#mandatory=true
#versionRange="[1.0.0,)"
#ordering="NONE"
#side="BOTH"

# Uncomment if using HZ Lib
#[[dependencies.${mod_id}]]
#modId="hzlib"
#mandatory=true
#versionRange="[1.0.0,)"
#ordering="NONE"
#side="BOTH"