# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.daemon=false

# IntelliJ IDEA is not yet fully compatible with configuration cache
org.gradle.configuration-cache=false

# Environment Properties
gradle_version=[6.0,6.2)
minecraft_version=1.19.4
minecraft_version_range=[1.19.4,1.20)

# Mappings
mapping_channel=official
mapping_version=1.19.4

# Forge Properties
# Check https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=45.4.0
forge_version_range=[45,)
loader_version_range=[45,)

# Fabric Properties
# Check https://fabricmc.net/develop
fabric_loader_version=0.17.3
fabric_yarn_mappings=1.19.4+build.2
fabric_api_version=0.87.2+1.19.4
loom_version=1.1-SNAPSHOT

# Mod Properties
mod_id=llovelyr
mod_name=LovelyRobot Legacy
mod_version=1.0
mod_group=net.msymbios.llovelyr
mod_authors=MSymbios
mod_license=MIT License
mod_description=Example mod description.
mod_page=https://www.curseforge.com/minecraft/mc-mods/reboot-lovelyrobot
mod_source=https://github.com/heria-zone/reboot-lovely-robot
mod_issues=https://github.com/heria-zone/reboot-lovely-robot/issues

# Legacy properties for compatibility
mod_group_id=${mod_group}
maven_group=${mod_group}