pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
        
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.7.0'
}

rootProject.name = "${mod_name} ${minecraft_version}"
include("Fabric", "Forge")
