modLoader="javafml"
loaderVersion="${forge_version_range}"
license="${lib_license}"
issueTrackerURL="${lib_issues}"

[[mods]]
modId="${lib_id}"
version="${lib_version}"
displayName="${lib_name}"
description='''${lib_description}'''
authors="${lib_authors}"
displayURL="${lib_homepage}"

[[dependencies.${lib_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${lib_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

# Uncomment if using GeckoLib
#[[dependencies.${lib_id}]]
#modId="geckolib"
#mandatory=true
#versionRange="[4.7.3,)"
#ordering="NONE"
#side="BOTH"

# Uncomment if depending on HZ Lib
#[[dependencies.${lib_id}]]
#modId="hzlib"
#mandatory=true
#versionRange="[1.0.0,)"
#ordering="NONE"
#side="BOTH"