package net.msymbios.llovelyr.source;

import com.mojang.brigadier.CommandDispatcher;
import com.mojang.brigadier.arguments.IntegerArgumentType;
import com.mojang.brigadier.builder.ArgumentBuilder;
import net.minecraft.command.argument.EntityArgumentType;
import net.minecraft.server.command.CommandManager;
import net.minecraft.server.command.ServerCommandSource;
import net.msymbios.llovelyr.common.commands.ColorArgumentType;
import net.msymbios.llovelyr.common.commands.NativeCommands;

/**
 * Centralizes command registration and execution for robot management.
 * <p>
 * <b>Architecture:</b> Uses Brigadier command tree structure to organize
 * hierarchical commands under "/llovely" root. Each command branch
 * handles specific robot management tasks (stats, enchantments, design).
 * <p>
 * <b>Permission Model:</b> All commands require OP level 2, preventing
 * unauthorized stat manipulation while allowing server administrators
 * full robot management capabilities.
 * <p>
 * <b>Entity Targeting:</b> Leverages Minecraft's EntityArgument for
 * flexible entity selection (@e, @p, @a, @r with type filters), enabling
 * batch operations on multiple robots simultaneously.
 */
public class LovelyCommands extends NativeCommands {

    // -- API Methods --

    public static void register(CommandDispatcher<ServerCommandSource> dispatcher) {
        dispatcher.register(
                CommandManager.literal("llovely")
                        .requires(source -> source.hasPermissionLevel(2))
                        .then(buildCrossCommands())
                        .then(buildTargetCommands())
                        .then(buildOwnerCommands())
                        .then(buildReloadCommand())
        );
    } // register ()

    // -- Internal Methods --

    private static ArgumentBuilder<ServerCommandSource, ?> buildCrossCommands() {
        return CommandManager.literal("robot")
                .then(buildCrossAddCommands())
                .then(buildCrossGetCommands())
                .then(buildCrossSetCommands())
                .then(CommandManager.literal("recall")
                        .executes(LovelyCommands::executeCrosshairRecall)
                )
                .then(CommandManager.literal("heal")
                        .executes(LovelyCommands::executeCrosshairHeal)
                )
                .then(CommandManager.literal("stats")
                        .executes(LovelyCommands::executeCrosshairStats)
                );
    } // buildCrossCommands()

    private static ArgumentBuilder<ServerCommandSource, ?> buildCrossAddCommands() {
        return CommandManager.literal("add")
                .then(buildCrossAddCombatCommands());
    } // buildCrossAddCommands()

    private static ArgumentBuilder<ServerCommandSource, ?> buildCrossSetCommands() {
        return CommandManager.literal("set")
                .then(buildCrossSetCombatCommands())
                .then(buildCrossSetAttributeCommands())
                .then(buildCrossSetProtectionCommands())
                .then(buildCrossSetAppearanceCommands())
                .then(buildCrossSetIdentifierCommands());
    } // buildCrossSetCommands ()


    private static ArgumentBuilder<ServerCommandSource, ?> buildTargetCommands() {
        return CommandManager.literal("target")
                .then(CommandManager.argument("targets", EntityArgumentType.entities())
                        .then(buildTargetAddCommands())
                        .then(buildTargetSetCommands())
                        .then(CommandManager.literal("heal").executes(LovelyCommands::executeTargetHeal))
                        .then(CommandManager.literal("teleport")
                                .then(CommandManager.argument("player", EntityArgumentType.player())
                                        .executes(LovelyCommands::executeTargetTeleport)
                                )
                        )
                        .then(CommandManager.literal("recall")
                                .then(CommandManager.argument("player", EntityArgumentType.player())
                                        .executes(LovelyCommands::executeTargetRecall)
                                )
                        )
                        .then(CommandManager.literal("ownership")
                                .then(CommandManager.argument("to_player", EntityArgumentType.player())
                                        .executes(LovelyCommands::executeTargetTransfer)
                                )
                        )
                );
    } // buildTargetCommands()

    private static ArgumentBuilder<ServerCommandSource, ?> buildTargetAddCommands() {
        return CommandManager.literal("add")
                .then(buildTargetAddCombatCommands());
    } // buildTargetAddCommands()

    private static ArgumentBuilder<ServerCommandSource, ?> buildTargetSetCommands() {
        return CommandManager.literal("set")
                .then(buildTargetSetCombatCommands())
                .then(buildTargetSetAttributeCommands())
                .then(buildTargetSetProtectionCommands())
                .then(buildTargetSetAppearanceCommands())
                .then(buildTargetSetIdentifierCommands());
    } // buildTargetSetCommands ()


    private static ArgumentBuilder<ServerCommandSource, ?> buildOwnerCommands() {
        return CommandManager.literal("owner")
                .then(buildOwnerListCommands())
                .then(buildOwnerAddCommands())
                .then(buildOwnerSetCommands())
                .then(CommandManager.literal("teleport")
                        .then(CommandManager.argument("player", EntityArgumentType.player())
                                .suggests(LovelyCommands::suggestPlayerNames)
                                .then(CommandManager.argument("robot_index", IntegerArgumentType.integer(0))
                                        .suggests(LovelyCommands::suggestRobotIndices)
                                        .executes(LovelyCommands::executeOwnerTeleport)
                                )
                        )
                )
                .then(CommandManager.literal("recall")
                        .then(CommandManager.argument("player", EntityArgumentType.player())
                                .suggests(LovelyCommands::suggestPlayerNames)
                                .then(CommandManager.argument("robot_index", IntegerArgumentType.integer(0))
                                        .suggests(LovelyCommands::suggestRobotIndices)
                                        .executes(LovelyCommands::executeOwnerRecall)
                                )
                        )
                )
                .then(CommandManager.literal("heal")
                        .then(CommandManager.argument("player", EntityArgumentType.player())
                                .suggests(LovelyCommands::suggestPlayerNames)
                                .then(CommandManager.argument("robot_index", IntegerArgumentType.integer(0))
                                        .suggests(LovelyCommands::suggestRobotIndices)
                                        .executes(LovelyCommands::executeOwnerHeal)
                                )
                        )
                )
                .then(CommandManager.literal("healall")
                        .then(CommandManager.argument("player", EntityArgumentType.player())
                                .suggests(LovelyCommands::suggestPlayerNames)
                                .executes(LovelyCommands::executeOwnerHealAll)
                        )
                )
                .then(CommandManager.literal("stats")
                        .then(CommandManager.argument("player", EntityArgumentType.player())
                                .suggests(LovelyCommands::suggestPlayerNames)
                                .then(CommandManager.argument("robot_index", IntegerArgumentType.integer(0))
                                        .suggests(LovelyCommands::suggestRobotIndices)
                                        .executes(LovelyCommands::executeOwnerStats)
                                )
                        )
                )
                .then(CommandManager.literal("transfer")
                        .then(CommandManager.argument("from_player", EntityArgumentType.player())
                                .suggests(LovelyCommands::suggestPlayerNames)
                                .then(CommandManager.argument("robot_index", IntegerArgumentType.integer(0))
                                        .suggests(LovelyCommands::suggestRobotIndices)
                                        .then(CommandManager.argument("to_player", EntityArgumentType.player())
                                                .executes(LovelyCommands::executeOwnerTransfer)
                                        )
                                )
                        )
                );
    } // buildOwnerCommands()

    private static ArgumentBuilder<ServerCommandSource, ?> buildOwnerListCommands() {
        return CommandManager.literal("list")
                .then(CommandManager.literal("player")
                        .executes(LovelyCommands::executeListOwners)
                )
                .then(CommandManager.literal("robot")
                        .then(CommandManager.argument("player", EntityArgumentType.player())
                                .executes(LovelyCommands::executeListPlayerRobots)
                        )
                );
    } // buildOwnerListCommands ()

    private static ArgumentBuilder<ServerCommandSource, ?> buildOwnerAddCommands() {
        return CommandManager.literal("add")
                .then(buildOwnerAddCombatCommands());
    } // buildOwnerAddCommands ()

    private static ArgumentBuilder<ServerCommandSource, ?> buildOwnerSetCommands() {
        return CommandManager.literal("set")
                .then(buildOwnerSetCombatCommands())
                .then(buildOwnerSetAttributeCommands())
                .then(buildOwnerSetProtectionCommands())
                .then(buildOwnerSetAppearanceCommands())
                .then(buildOwnerSetIdentifierCommands());
    } // buildOwnerSetCommands ()

    // TARGET COMMANDS
    private static ArgumentBuilder<ServerCommandSource, ?> buildTargetAddCombatCommands () {
        return CommandManager.literal("combat")
                .then(CommandManager.literal("exp")
                        .then(CommandManager.argument("exp_value", IntegerArgumentType.integer(0))
                                .suggests(LovelyCommands::suggestMinMaxExp)
                                .executes(LovelyCommands::executeTargetAddXP)
                        )
                );
    } // buildTargetAddCombatCommands ()

    private static ArgumentBuilder<ServerCommandSource, ?> buildTargetSetCombatCommands () {
        return CommandManager.literal("combat")
                .then(CommandManager.literal("all")
                        .then(CommandManager.argument("level", IntegerArgumentType.integer(1))
                                .suggests(LovelyCommands::suggestMinMaxLevel)
                                .then(CommandManager.argument("exp", IntegerArgumentType.integer(0))
                                        .suggests(LovelyCommands::suggestMinMaxExpForLevel)
                                        .executes(LovelyCommands::executeTargetSetAllCombat)
                                )
                        )
                )
                .then(CommandManager.literal("exp")
                        .then(CommandManager.argument("exp_value", IntegerArgumentType.integer(0))
                                .suggests(LovelyCommands::suggestMinMaxExp)
                                .executes(LovelyCommands::executeTargetSetXP)
                        )
                )
                .then(CommandManager.literal("level")
                        .then(CommandManager.argument("level_value", IntegerArgumentType.integer(1))
                                .suggests(LovelyCommands::suggestMinMaxLevel)
                                .executes(LovelyCommands::executeTargetSetLevel)
                        )
                );
    } // buildTargetSetCombatCommands ()

    private static ArgumentBuilder<ServerCommandSource, ?> buildTargetSetAttributeCommands() {
        return CommandManager.literal("attribute")
                .then(CommandManager.literal("all")
                        .then(CommandManager.argument("hp", IntegerArgumentType.integer(1))
                                .then(CommandManager.argument("attack", IntegerArgumentType.integer(1))
                                        .then(CommandManager.argument("defense", IntegerArgumentType.integer(0))
                                                .then(CommandManager.argument("speed", IntegerArgumentType.integer(1))
                                                        .executes(LovelyCommands::executeTargetSetAllAttributes)
                                                )
                                        )
                                )
                        )
                )
                .then(CommandManager.literal("hp")
                        .then(CommandManager.argument("value", IntegerArgumentType.integer(1))
                                .executes(LovelyCommands::executeTargetSetHP)
                        )
                )
                .then(CommandManager.literal("attack")
                        .then(CommandManager.argument("value", IntegerArgumentType.integer(1))
                                .executes(LovelyCommands::executeTargetSetAttack)
                        )
                )
                .then(CommandManager.literal("defense")
                        .then(CommandManager.argument("value", IntegerArgumentType.integer(0))
                                .executes(LovelyCommands::executeTargetSetDefense)
                        )
                )
                .then(CommandManager.literal("speed")
                        .then(CommandManager.argument("value", IntegerArgumentType.integer(1))
                                .executes(LovelyCommands::executeTargetSetSpeed)
                        )
                );
    } // buildTargetSetAttributeCommands()

    private static ArgumentBuilder<ServerCommandSource, ?> buildTargetSetProtectionCommands() {
        return CommandManager.literal("protection")
                .then(CommandManager.literal("all")
                        .then(CommandManager.argument("fire", IntegerArgumentType.integer(0))
                                .suggests((ctx, builder) -> suggestMinMaxProtection(ctx, builder, "fire"))
                                .then(CommandManager.argument("fall", IntegerArgumentType.integer(0))
                                        .suggests((ctx, builder) -> suggestMinMaxProtection(ctx, builder, "fall"))
                                        .then(CommandManager.argument("blast", IntegerArgumentType.integer(0))
                                                .suggests((ctx, builder) -> suggestMinMaxProtection(ctx, builder, "blast"))
                                                .then(CommandManager.argument("projectile", IntegerArgumentType.integer(0))
                                                        .suggests((ctx, builder) -> suggestMinMaxProtection(ctx, builder, "projectile"))
                                                        .executes(LovelyCommands::executeTargetSetAllProtections)
                                                )
                                        )
                                )
                        )
                )
                .then(CommandManager.literal("fire")
                        .then(CommandManager.argument("level", IntegerArgumentType.integer(0))
                                .suggests((ctx, builder) -> suggestMinMaxProtection(ctx, builder, "fire"))
                                .executes(LovelyCommands::executeTargetSetFireProtection)
                        )
                )
                .then(CommandManager.literal("fall")
                        .then(CommandManager.argument("level", IntegerArgumentType.integer(0))
                                .suggests((ctx, builder) -> suggestMinMaxProtection(ctx, builder, "fall"))
                                .executes(LovelyCommands::executeTargetSetFallProtection)
                        )
                )
                .then(CommandManager.literal("blast")
                        .then(CommandManager.argument("level", IntegerArgumentType.integer(0))
                                .suggests((ctx, builder) -> suggestMinMaxProtection(ctx, builder, "blast"))
                                .executes(LovelyCommands::executeTargetSetBlastProtection)
                        )
                )
                .then(CommandManager.literal("projectile")
                        .then(CommandManager.argument("level", IntegerArgumentType.integer(0))
                                .suggests((ctx, builder) -> suggestMinMaxProtection(ctx, builder, "projectile"))
                                .executes(LovelyCommands::executeTargetSetProjectileProtection)
                        )
                );
    } // buildTargetSetProtectionCommands()

    private static ArgumentBuilder<ServerCommandSource, ?> buildTargetSetAppearanceCommands() {
        return CommandManager.literal("appearance")
                .then(CommandManager.argument("color", ColorArgumentType.color())
                        .executes(LovelyCommands::executeTargetSetAppearance)
                );
    } // buildTargetSetAppearanceCommands()

    private static ArgumentBuilder<ServerCommandSource, ?> buildTargetSetIdentifierCommands() {
        return CommandManager.literal("identifier")
                .then(CommandManager.argument("name", com.mojang.brigadier.arguments.StringArgumentType.greedyString())
                        .executes(LovelyCommands::executeTargetSetIdentifier)
                );
    } // buildTargetSetIdentifierCommands()

    // CROSS-AIR COMMANDS
    private static ArgumentBuilder<ServerCommandSource, ?> buildCrossAddCombatCommands() {
        return CommandManager.literal("combat")
                .then(CommandManager.literal("exp")
                        .then(CommandManager.argument("exp_value", IntegerArgumentType.integer(0))
                                .suggests(LovelyCommands::suggestMaxExp)
                                .executes(LovelyCommands::executeCrosshairAddXP)
                        )
                );
    } // buildRobotCombatCommands()

    private static ArgumentBuilder<ServerCommandSource, ?> buildCrossSetCombatCommands () {
        return CommandManager.literal("combat")
                .then(CommandManager.literal("all")
                        .then(CommandManager.argument("level", IntegerArgumentType.integer(1))
                                .suggests(LovelyCommands::suggestMaxLevel)
                                .then(CommandManager.argument("exp", IntegerArgumentType.integer(0))
                                        .suggests(LovelyCommands::suggestMaxExpForLevel)
                                        .executes(LovelyCommands::executeSetAllCombat)
                                )
                        )
                )
                .then(CommandManager.literal("exp")
                        .then(CommandManager.argument("exp_value", IntegerArgumentType.integer(0))
                                .suggests(LovelyCommands::suggestMaxExp)
                                .executes(LovelyCommands::executeCrosshairSetXP)
                        )
                )
                .then(CommandManager.literal("level")
                        .then(CommandManager.argument("level_value", IntegerArgumentType.integer(1))
                                .suggests(LovelyCommands::suggestMaxLevel)
                                .executes(LovelyCommands::executeCrosshairSetLevel)
                        )
                );
    } // buildCrossSetCombatCommands ()

    private static ArgumentBuilder<ServerCommandSource, ?> buildCrossSetAttributeCommands() {
        return CommandManager.literal("attribute")
                .then(CommandManager.literal("all")
                        .then(CommandManager.argument("hp", IntegerArgumentType.integer(1))
                                .then(CommandManager.argument("attack", IntegerArgumentType.integer(1))
                                        .then(CommandManager.argument("defense", IntegerArgumentType.integer(0))
                                                .then(CommandManager.argument("speed", IntegerArgumentType.integer(1))
                                                        .executes(LovelyCommands::executeCrosshairSetAllAttributes)
                                                )
                                        )
                                )
                        )
                )
                .then(CommandManager.literal("hp")
                        .then(CommandManager.argument("value", IntegerArgumentType.integer(1))
                                .executes(LovelyCommands::executeCrosshairSetHP)
                        )
                )
                .then(CommandManager.literal("attack")
                        .then(CommandManager.argument("value", IntegerArgumentType.integer(1))
                                .executes(LovelyCommands::executeCrosshairSetAttack)
                        )
                )
                .then(CommandManager.literal("defense")
                        .then(CommandManager.argument("value", IntegerArgumentType.integer(0))
                                .executes(LovelyCommands::executeCrosshairSetDefense)
                        )
                )
                .then(CommandManager.literal("speed")
                        .then(CommandManager.argument("value", IntegerArgumentType.integer(1))
                                .executes(LovelyCommands::executeCrosshairSetSpeed)
                        )
                );
    } // buildCrossSetAttributeCommands()

    private static ArgumentBuilder<ServerCommandSource, ?> buildCrossSetProtectionCommands() {
        return CommandManager.literal("protection")
                .then(CommandManager.literal("all")
                        .then(CommandManager.argument("fire", IntegerArgumentType.integer(0))
                                .suggests(LovelyCommands::suggestMaxFireProtection)
                                .then(CommandManager.argument("fall", IntegerArgumentType.integer(0))
                                        .suggests(LovelyCommands::suggestMaxFallProtection)
                                        .then(CommandManager.argument("blast", IntegerArgumentType.integer(0))
                                                .suggests(LovelyCommands::suggestMaxBlastProtection)
                                                .then(CommandManager.argument("projectile", IntegerArgumentType.integer(0))
                                                        .suggests(LovelyCommands::suggestMaxProjectileProtection)
                                                        .executes(LovelyCommands::executeCrosshairSetAllProtections)
                                                )
                                        )
                                )
                        )
                )
                .then(CommandManager.literal("fire")
                        .then(CommandManager.argument("level", IntegerArgumentType.integer(0))
                                .suggests(LovelyCommands::suggestMaxFireProtection)
                                .executes(LovelyCommands::executeCrosshairSetFireProtection)
                        )
                )
                .then(CommandManager.literal("fall")
                        .then(CommandManager.argument("level", IntegerArgumentType.integer(0))
                                .suggests(LovelyCommands::suggestMaxFallProtection)
                                .executes(LovelyCommands::executeCrosshairSetFallProtection)
                        )
                )
                .then(CommandManager.literal("blast")
                        .then(CommandManager.argument("level", IntegerArgumentType.integer(0))
                                .suggests(LovelyCommands::suggestMaxBlastProtection)
                                .executes(LovelyCommands::executeCrosshairSetBlastProtection)
                        )
                )
                .then(CommandManager.literal("projectile")
                        .then(CommandManager.argument("level", IntegerArgumentType.integer(0))
                                .suggests(LovelyCommands::suggestMaxProjectileProtection)
                                .executes(LovelyCommands::executeCrosshairSetProjectileProtection)
                        )
                );
    } // buildCrossSetProtectionCommands()

    private static ArgumentBuilder<ServerCommandSource, ?> buildCrossSetAppearanceCommands() {
        return CommandManager.literal("appearance")
                .then(CommandManager.argument("color", ColorArgumentType.color())
                        .executes(LovelyCommands::executeCrosshairSetAppearance)
                );
    } // buildCrossSetAppearanceCommands()

    private static ArgumentBuilder<ServerCommandSource, ?> buildCrossSetIdentifierCommands() {
        return CommandManager.literal("identifier")
                .then(CommandManager.argument("name", com.mojang.brigadier.arguments.StringArgumentType.greedyString())
                        .executes(LovelyCommands::executeCrosshairSetIdentifier)
                );
    } // buildCrossSetIdentifierCommands()

    private static ArgumentBuilder<ServerCommandSource, ?> buildCrossGetCommands() {
        return CommandManager.literal("get")
                .then(CommandManager.literal("owner")
                        .executes(LovelyCommands::executeCrosshairGetOwner)
                );
    } // buildCrossGetCommands()

    // OWNER COMMANDS
    private static ArgumentBuilder<ServerCommandSource, ?> buildOwnerAddCombatCommands() {
        return CommandManager.literal("combat")
                .then(CommandManager.literal("exp")
                        .then(CommandManager.argument("player", EntityArgumentType.player())
                                .suggests(LovelyCommands::suggestPlayerNames)
                                .then(CommandManager.argument("robot_index", IntegerArgumentType.integer(0))
                                        .suggests(LovelyCommands::suggestRobotIndices)
                                        .then(CommandManager.argument("exp_value", IntegerArgumentType.integer(0))
                                                .suggests(LovelyCommands::suggestOwnerMaxExp)
                                                .executes(LovelyCommands::executeOwnerAddExp)
                                        )
                                )
                        )
                );
    } // buildOwnerAddCombatCommands ()

    private static ArgumentBuilder<ServerCommandSource, ?> buildOwnerSetCombatCommands () {
        return CommandManager.literal("combat")
                .then(CommandManager.literal("all")
                        .then(CommandManager.argument("player", EntityArgumentType.player())
                                .suggests(LovelyCommands::suggestPlayerNames)
                                .then(CommandManager.argument("robot_index", IntegerArgumentType.integer(0))
                                        .suggests(LovelyCommands::suggestRobotIndices)
                                        .then(CommandManager.argument("level", IntegerArgumentType.integer(1))
                                                .suggests(LovelyCommands::suggestOwnerMaxLevel)
                                                .then(CommandManager.argument("exp", IntegerArgumentType.integer(0))
                                                        .suggests(LovelyCommands::suggestOwnerMaxExpForLevel)
                                                        .executes(LovelyCommands::executeOwnerSetAllCombat)
                                                )
                                        )
                                )
                        )
                )
                .then(CommandManager.literal("exp")
                        .then(CommandManager.argument("player", EntityArgumentType.player())
                                .suggests(LovelyCommands::suggestPlayerNames)
                                .then(CommandManager.argument("robot_index", IntegerArgumentType.integer(0))
                                        .suggests(LovelyCommands::suggestRobotIndices)
                                        .then(CommandManager.argument("exp_value", IntegerArgumentType.integer(0))
                                                .suggests(LovelyCommands::suggestOwnerMaxExp)
                                                .executes(LovelyCommands::executeOwnerSetExp)
                                        )
                                )
                        )
                )
                .then(CommandManager.literal("level")
                        .then(CommandManager.argument("player", EntityArgumentType.player())
                                .suggests(LovelyCommands::suggestPlayerNames)
                                .then(CommandManager.argument("robot_index", IntegerArgumentType.integer(0))
                                        .suggests(LovelyCommands::suggestRobotIndices)
                                        .then(CommandManager.argument("level_value", IntegerArgumentType.integer(1))
                                                .suggests(LovelyCommands::suggestOwnerMaxLevel)
                                                .executes(LovelyCommands::executeOwnerSetLevel)
                                        )
                                )
                        )
                );
    } // buildOwnerSetCombatCommands ()

    private static ArgumentBuilder<ServerCommandSource, ?> buildOwnerSetAttributeCommands() {
        return CommandManager.literal("attribute")
                .then(CommandManager.literal("all")
                        .then(CommandManager.argument("player", EntityArgumentType.player())
                                .suggests(LovelyCommands::suggestPlayerNames)
                                .then(CommandManager.argument("robot_index", IntegerArgumentType.integer(0))
                                        .suggests(LovelyCommands::suggestRobotIndices)
                                        .then(CommandManager.argument("hp", IntegerArgumentType.integer(1))
                                                .then(CommandManager.argument("attack", IntegerArgumentType.integer(1))
                                                        .then(CommandManager.argument("defense", IntegerArgumentType.integer(0))
                                                                .then(CommandManager.argument("speed", IntegerArgumentType.integer(1))
                                                                        .executes(LovelyCommands::executeOwnerSetAllAttributes)
                                                                )
                                                        )
                                                )
                                        )
                                )
                        )
                )
                .then(CommandManager.literal("hp")
                        .then(CommandManager.argument("player", EntityArgumentType.player())
                                .suggests(LovelyCommands::suggestPlayerNames)
                                .then(CommandManager.argument("robot_index", IntegerArgumentType.integer(0))
                                        .suggests(LovelyCommands::suggestRobotIndices)
                                        .then(CommandManager.argument("value", IntegerArgumentType.integer(1))
                                                .executes(LovelyCommands::executeOwnerSetHP)
                                        )
                                )
                        )
                )
                .then(CommandManager.literal("attack")
                        .then(CommandManager.argument("player", EntityArgumentType.player())
                                .suggests(LovelyCommands::suggestPlayerNames)
                                .then(CommandManager.argument("robot_index", IntegerArgumentType.integer(0))
                                        .suggests(LovelyCommands::suggestRobotIndices)
                                        .then(CommandManager.argument("value", IntegerArgumentType.integer(1))
                                                .executes(LovelyCommands::executeOwnerSetAttack)
                                        )
                                )
                        )
                )
                .then(CommandManager.literal("defense")
                        .then(CommandManager.argument("player", EntityArgumentType.player())
                                .suggests(LovelyCommands::suggestPlayerNames)
                                .then(CommandManager.argument("robot_index", IntegerArgumentType.integer(0))
                                        .suggests(LovelyCommands::suggestRobotIndices)
                                        .then(CommandManager.argument("value", IntegerArgumentType.integer(0))
                                                .executes(LovelyCommands::executeOwnerSetDefense)
                                        )
                                )
                        )
                )
                .then(CommandManager.literal("speed")
                        .then(CommandManager.argument("player", EntityArgumentType.player())
                                .suggests(LovelyCommands::suggestPlayerNames)
                                .then(CommandManager.argument("robot_index", IntegerArgumentType.integer(0))
                                        .suggests(LovelyCommands::suggestRobotIndices)
                                        .then(CommandManager.argument("value", IntegerArgumentType.integer(1))
                                                .executes(LovelyCommands::executeOwnerSetSpeed)
                                        )
                                )
                        )
                );
    } // buildOwnerSetAttributeCommands()

    private static ArgumentBuilder<ServerCommandSource, ?> buildOwnerSetProtectionCommands() {
        return CommandManager.literal("protection")
                .then(CommandManager.literal("all")
                        .then(CommandManager.argument("player", EntityArgumentType.player())
                                .suggests(LovelyCommands::suggestPlayerNames)
                                .then(CommandManager.argument("robot_index", IntegerArgumentType.integer(0))
                                        .suggests(LovelyCommands::suggestRobotIndices)
                                        .then(CommandManager.argument("fire", IntegerArgumentType.integer(0))
                                                .suggests((ctx, builder) -> suggestOwnerMaxProtection(ctx, builder, "fire"))
                                                .then(CommandManager.argument("fall", IntegerArgumentType.integer(0))
                                                        .suggests((ctx, builder) -> suggestOwnerMaxProtection(ctx, builder, "fall"))
                                                        .then(CommandManager.argument("blast", IntegerArgumentType.integer(0))
                                                                .suggests((ctx, builder) -> suggestOwnerMaxProtection(ctx, builder, "blast"))
                                                                .then(CommandManager.argument("projectile", IntegerArgumentType.integer(0))
                                                                        .suggests((ctx, builder) -> suggestOwnerMaxProtection(ctx, builder, "projectile"))
                                                                        .executes(LovelyCommands::executeOwnerSetAllProtections)
                                                                )
                                                        )
                                                )
                                        )
                                )
                        )
                )
                .then(CommandManager.literal("fire")
                        .then(CommandManager.argument("player", EntityArgumentType.player())
                                .suggests(LovelyCommands::suggestPlayerNames)
                                .then(CommandManager.argument("robot_index", IntegerArgumentType.integer(0))
                                        .suggests(LovelyCommands::suggestRobotIndices)
                                        .then(CommandManager.argument("level", IntegerArgumentType.integer(0))
                                                .suggests((ctx, builder) -> suggestOwnerMaxProtection(ctx, builder, "fire"))
                                                .executes(LovelyCommands::executeOwnerSetFireProtection)
                                        )
                                )
                        )
                )
                .then(CommandManager.literal("fall")
                        .then(CommandManager.argument("player", EntityArgumentType.player())
                                .suggests(LovelyCommands::suggestPlayerNames)
                                .then(CommandManager.argument("robot_index", IntegerArgumentType.integer(0))
                                        .suggests(LovelyCommands::suggestRobotIndices)
                                        .then(CommandManager.argument("level", IntegerArgumentType.integer(0))
                                                .suggests((ctx, builder) -> suggestOwnerMaxProtection(ctx, builder, "fall"))
                                                .executes(LovelyCommands::executeOwnerSetFallProtection)
                                        )
                                )
                        )
                )
                .then(CommandManager.literal("blast")
                        .then(CommandManager.argument("player", EntityArgumentType.player())
                                .suggests(LovelyCommands::suggestPlayerNames)
                                .then(CommandManager.argument("robot_index", IntegerArgumentType.integer(0))
                                        .suggests(LovelyCommands::suggestRobotIndices)
                                        .then(CommandManager.argument("level", IntegerArgumentType.integer(0))
                                                .suggests((ctx, builder) -> suggestOwnerMaxProtection(ctx, builder, "blast"))
                                                .executes(LovelyCommands::executeOwnerSetBlastProtection)
                                        )
                                )
                        )
                )
                .then(CommandManager.literal("projectile")
                        .then(CommandManager.argument("player", EntityArgumentType.player())
                                .suggests(LovelyCommands::suggestPlayerNames)
                                .then(CommandManager.argument("robot_index", IntegerArgumentType.integer(0))
                                        .suggests(LovelyCommands::suggestRobotIndices)
                                        .then(CommandManager.argument("level", IntegerArgumentType.integer(0))
                                                .suggests((ctx, builder) -> suggestOwnerMaxProtection(ctx, builder, "projectile"))
                                                .executes(LovelyCommands::executeOwnerSetProjectileProtection)
                                        )
                                )
                        )
                );
    } // buildOwnerSetProtectionCommands()

    private static ArgumentBuilder<ServerCommandSource, ?> buildOwnerSetAppearanceCommands() {
        return CommandManager.literal("appearance")
                .then(CommandManager.argument("player", EntityArgumentType.player())
                        .suggests(LovelyCommands::suggestPlayerNames)
                        .then(CommandManager.argument("robot_index", IntegerArgumentType.integer(0))
                                .suggests(LovelyCommands::suggestRobotIndices)
                                .then(CommandManager.argument("color", ColorArgumentType.color())
                                        .executes(LovelyCommands::executeOwnerSetAppearance)
                                )
                        )
                );
    } // buildOwnerSetAppearanceCommands()

    private static ArgumentBuilder<ServerCommandSource, ?> buildOwnerSetIdentifierCommands() {
        return CommandManager.literal("identifier")
                .then(CommandManager.argument("player", EntityArgumentType.player())
                        .suggests(LovelyCommands::suggestPlayerNames)
                        .then(CommandManager.argument("robot_index", IntegerArgumentType.integer(0))
                                .suggests(LovelyCommands::suggestRobotIndices)
                                .then(CommandManager.argument("name", com.mojang.brigadier.arguments.StringArgumentType.greedyString())
                                        .executes(LovelyCommands::executeOwnerSetIdentifier)
                                )
                        )
                );
    } // buildOwnerSetIdentifierCommands()

    private static ArgumentBuilder<ServerCommandSource, ?> buildReloadCommand() {
        return CommandManager.literal("reload")
                .executes(LovelyCommands::executeReload);
    } // buildReloadCommand()

} // Class: LovelyCommands

