pluginManagement {

    repositories {
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }

        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }

        mavenCentral()
        gradlePluginPortal()
    }
}

buildscript {
    repositories {
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
    }
}

rootProject.name = "${mod_name} ${minecraft_version}"
include("Fabric")